import json, os

base = 'src/i18n'

with open(os.path.join(base, 'id.json'), encoding='utf-8') as f:
    id_data = json.load(f)
with open(os.path.join(base, 'en.json'), encoding='utf-8') as f:
    en_data = json.load(f)
with open(os.path.join(base, 'ar.json'), encoding='utf-8') as f:
    ar_data = json.load(f)

new_keys = [
    ("prayerPageTitle", "Jadwal Sholat", "Prayer Schedule", "جدول الصلاة"),
    ("prayerPageSubtitle", "Waktu sholat berdasarkan lokasi Anda", "Prayer times based on your location", "أوقات الصلاة حسب موقعك"),
    ("nextPrayerTime", "Waktu Sholat Selanjutnya", "Next Prayer Time", "وقت الصلاة القادمة"),
    ("allPrayersComplete", "Sholat hari ini telah selesai", "Today's prayers are complete", "انتهت صلوات اليوم"),
    ("tomorrow", "Besok", "Tomorrow", "غداً"),
    ("detectingLocation", "Mendeteksi lokasi Anda...", "Detecting your location...", "جاري تحديد موقعك..."),
    ("locationDenied", "Izin lokasi ditolak. Silakan pilih kota secara manual.", "Location permission denied. Please select a city manually.", "تم رفض إذن الموقع. الرجاء اختيار مدينة يدوياً."),
    ("locationUnavailable", "GPS tidak tersedia. Silakan pilih kota secara manual.", "GPS unavailable. Please select a city manually.", "GPS غير متاح. الرجاء اختيار مدينة يدوياً."),
    ("province", "Provinsi", "Province", "المحافظة"),
    ("city", "Kota/Kabupaten", "City/Regency", "المدينة/المنطقة"),
    ("selectProvince", "-- Pilih Provinsi --", "-- Select Province --", "-- اختر المحافظة --"),
    ("selectCity", "-- Pilih Kota --", "-- Select City --", "-- اختر المدينة --"),
    ("redetect", "Deteksi Ulang", "Re-detect", "إعادة الكشف"),
    ("now", "SEKARANG", "NOW", "الآن"),
    ("nextLabel", "Berikutnya", "Next", "التالي"),
    ("pastLabel", "Sudah", "Passed", "مضى"),
    ("upcomingLabel", "Akan tiba", "Upcoming", "قادم"),
    ("selectLocationPrompt", "Pilih provinsi dan kota untuk menampilkan jadwal sholat.", "Select province and city to display prayer schedule.", "اختر المحافظة والمدينة لعرض جدول الصلاة."),
    ("scheduleUnavailable", "Jadwal tidak tersedia untuk lokasi ini.", "Schedule not available for this location.", "الجدول غير متاح لهذا الموقع."),
    ("materialsListTitle", "Materi Kajian", "Study Materials", "مواد الدراسة"),
    ("materialsListSubtitle", "Pelajari materi Ramadan yang tersedia", "Learn available Ramadan materials", "تعلم مواد رمضان المتاحة"),
    ("searchMaterials", "Cari materi...", "Search materials...", "ابحث عن مواد..."),
    ("allFilter", "Semua", "All", "الكل"),
    ("noDescription", "Tidak ada deskripsi", "No description", "لا يوجد وصف"),
    ("generalCategory", "Umum", "General", "عام"),
    ("noMaterials", "Belum ada materi tersedia.", "No materials available.", "لا توجد مواد متاحة."),
    ("pdfFile", "File PDF", "PDF File", "ملف PDF"),
    ("openFile", "Buka file", "Open file", "فتح الملف"),
    ("articleType", "Artikel", "Article", "مقال"),
    ("readFull", "Baca selengkapnya", "Read more", "اقرأ المزيد"),
    ("quizNotFound", "Quiz tidak ditemukan.", "Quiz not found.", "الاختبار غير موجود."),
    ("backToQuizList", "Kembali ke Quiz", "Back to Quiz", "العودة إلى الاختبار"),
    ("question", "Soal", "Question", "سؤال"),
    ("passingGrade", "Minimal Lulus", "Passing Grade", "درجة النجاح"),
    ("congratulations", "Selamat, Anda Lulus!", "Congratulations, You Passed!", "تهانينا، لقد نجحت!"),
    ("notPassed", "Belum Berhasil", "Not Passed", "لم تنجح"),
    ("correct", "Benar", "Correct", "صحيح"),
    ("answered", "terjawab", "answered", "تمت الإجابة"),
    ("points", "poin", "points", "نقاط"),
    ("submitAnswers", "Kumpulkan Jawaban", "Submit Answers", "تقديم الإجابات"),
    ("failedToSubmit", "Gagal mengirim jawaban", "Failed to submit answers", "فشل في تقديم الإجابات"),
    ("noTimeLimit", "tanpa batas", "no time limit", "بدون حد زمني"),
    ("manageSermonTitle", "Materi Khotbah Jumat", "Friday Sermon Materials", "مواد خطبة الجمعة"),
    ("manageSermonSubtitle", "Kelola judul dan materi khotbah Jumat", "Manage Friday sermon topics and materials", "إدارة مواضيع ومواد خطبة الجمعة"),
    ("addSermon", "Tambah Materi", "Add Material", "إضافة مادة"),
    ("editSermon", "Edit Materi Khotbah", "Edit Sermon Material", "تعديل مادة الخطبة"),
    ("addNewSermon", "Tambah Materi Khotbah Baru", "Add New Sermon Material", "إضافة مادة خطبة جديدة"),
    ("sermonTitleField", "Judul Materi", "Material Title", "عنوان المادة"),
    ("sermonDescription", "Deskripsi", "Description", "الوصف"),
    ("sermonPlaceholder", "Masukkan judul khotbah", "Enter sermon title", "أدخل عنوان الخطبة"),
    ("descriptionPlaceholder", "Deskripsi materi khotbah", "Sermon material description", "وصف مادة الخطبة"),
    ("confirmDeleteSermon", "Hapus materi khotbah ini?", "Delete this sermon material?", "حذف مادة الخطبة هذه؟"),
    ("successSavedSermon", "Materi berhasil diubah!", "Material updated successfully!", "تم تحديث المادة بنجاح!"),
    ("successAddedSermon", "Materi berhasil ditambahkan!", "Material added successfully!", "تمت إضافة المادة بنجاح!"),
    ("successDeletedSermon", "Materi berhasil dihapus!", "Material deleted successfully!", "تم حذف المادة بنجاح!"),
    ("errorLoadSermon", "Gagal memuat data.", "Failed to load data.", "فشل في تحميل البيانات."),
    ("errorSaveSermon", "Gagal menyimpan materi.", "Failed to save material.", "فشل في حفظ المادة."),
    ("errorDeleteSermon", "Gagal menghapus materi.", "Failed to delete material.", "فشل في حذف المادة."),
    ("noSermonData", "Belum ada materi khotbah.", "No sermon materials yet.", "لا توجد مواد خطبة بعد."),
    ("titleRequired", "Judul wajib diisi", "Title is required", "العنوان مطلوب"),
    ("manageStudentsTitle", "Kelola Siswa", "Manage Students", "إدارة الطلاب"),
    ("manageStudentsSubtitle", "CRUD data siswa, import, export, dan reset password", "CRUD student data, import, export, and password reset", "إدارة بيانات الطلاب، الاستيراد، التصدير، وإعادة تعيين كلمة المرور"),
    ("addStudent", "Tambah Siswa", "Add Student", "إضافة طالب"),
    ("importStudents", "Import", "Import", "استيراد"),
    ("exportStudents", "Export", "Export", "تصدير"),
    ("importTitle", "Import Siswa", "Import Students", "استيراد الطلاب"),
    ("importFormat", "Format: nama,nisn,kelas,password (setiap baris = 1 siswa)", "Format: name,nisn,class,password (each line = 1 student)", "التنسيق: الاسم،nisn،الفصل،كلمة المرور (كل سطر = طالب واحد)"),
    ("importButton", "Import", "Import", "استيراد"),
    ("searchStudentPlaceholder", "Cari nama atau NISN...", "Search name or NISN...", "ابحث عن اسم أو NISN..."),
    ("editStudent", "Edit Siswa", "Edit Student", "تعديل الطالب"),
    ("addNewStudent", "Tambah Siswa Baru", "Add New Student", "إضافة طالب جديد"),
    ("name", "Nama", "Name", "الاسم"),
    ("nameRequired", "Nama dan NISN wajib diisi", "Name and NISN are required", "الاسم و NISN مطلوبان"),
    ("passwordMinLength", "Password minimal 6 karakter", "Password minimum 6 characters", "كلمة المرور 6 أحرف على الأقل"),
    ("confirmDeleteStudent", "Hapus siswa ini?", "Delete this student?", "حذف هذا الطالب؟"),
    ("successStudentSaved", "Siswa berhasil diubah!", "Student updated successfully!", "تم تحديث الطالب بنجاح!"),
    ("successStudentAdded", "Siswa berhasil ditambahkan!", "Student added successfully!", "تمت إضافة الطالب بنجاح!"),
    ("successStudentDeleted", "Siswa dihapus!", "Student deleted!", "تم حذف الطالب!"),
    ("successPasswordReset", "Password direset!", "Password reset!", "تم إعادة تعيين كلمة المرور!"),
    ("errorLoadStudents", "Gagal memuat data", "Failed to load data", "فشل تحميل البيانات"),
    ("errorSaveStudent", "Gagal menyimpan", "Failed to save", "فشل الحفظ"),
    ("errorDeleteStudent", "Gagal menghapus", "Failed to delete", "فشل الحذف"),
    ("errorResetPassword", "Gagal reset password", "Failed to reset password", "فشل إعادة تعيين كلمة المرور"),
    ("errorImport", "Gagal import. Format: nama,nisn,kelas,password", "Import failed. Format: name,nisn,class,password", "فشل الاستيراد. التنسيق: الاسم،nisn،الفصل،كلمة المرور"),
    ("errorExport", "Gagal export", "Export failed", "فشل التصدير"),
    ("noStudentData", "Tidak ada data siswa.", "No student data.", "لا توجد بيانات طلاب."),
    ("emptyPasswordHint", "(kosongkan jika tidak diubah)", "(leave blank if unchanged)", "(اتركه فارغاً إذا لم يتغير)"),
    ("minLengthHint", "Minimal 6 karakter", "Minimum 6 characters", "6 أحرف على الأقل"),
    ("fullNamePlaceholder", "Nama lengkap", "Full name", "الاسم الكامل"),
    ("nisnPlaceholder", "NISN", "NISN", "NISN"),
    ("classNameLabel", "Kelas {name}", "Class {name}", "الفصل {name}"),
    ("manageMaterialsTitle", "Kelola Materi Ramadan", "Manage Ramadan Materials", "إدارة مواد رمضان"),
    ("manageMaterialsSubtitle", "Buat dan kelola materi pembelajaran", "Create and manage learning materials", "إنشاء وإدارة مواد التعلم"),
    ("addMaterial", "Tambah Materi", "Add Material", "إضافة مادة"),
    ("addCategory", "+ Kategori", "+ Category", "+ فئة"),
    ("newCategoryName", "Nama kategori baru", "New category name", "اسم الفئة الجديدة"),
    ("addCategoryLabel", "Tambah", "Add", "إضافة"),
    ("editMaterial", "Edit Materi", "Edit Material", "تعديل المادة"),
    ("addNewMaterial", "Tambah Materi Baru", "Add New Material", "إضافة مادة جديدة"),
    ("typeLabel", "Tipe", "Type", "النوع"),
    ("selectCategory", "-- Pilih Kategori --", "-- Select Category --", "-- اختر الفئة --"),
    ("urlFile", "URL File/Thumbnail", "File URL/Thumbnail", "رابط الملف/الصورة المصغرة"),
    ("uploadPdf", "Upload PDF", "Upload PDF", "رفع PDF"),
    ("pdfUrl", "URL PDF atau upload file", "PDF URL or upload file", "رابط PDF أو رفع ملف"),
    ("videoUrl", "URL Video (YouTube embed)", "Video URL (YouTube embed)", "رابط الفيديو (YouTube embed)"),
    ("successMaterialAdded", "Materi ditambahkan!", "Material added!", "تمت إضافة المادة!"),
    ("successMaterialUpdated", "Materi diubah!", "Material updated!", "تم تحديث المادة!"),
    ("successCategoryAdded", "Kategori ditambahkan!", "Category added!", "تمت إضافة الفئة!"),
    ("successMaterialDeleted", "Materi dihapus!", "Material deleted!", "تم حذف المادة!"),
    ("errorLoadMaterials", "Gagal memuat data", "Failed to load data", "فشل تحميل البيانات"),
    ("errorSaveMaterial", "Gagal menyimpan", "Failed to save", "فشل الحفظ"),
    ("errorDeleteMaterial", "Gagal menghapus", "Failed to delete", "فشل الحذف"),
    ("errorAddCategory", "Gagal menambah kategori", "Failed to add category", "فشل إضافة الفئة"),
    ("errorUploadFile", "Gagal upload file", "Failed to upload file", "فشل رفع الملف"),
    ("noMaterialData", "Belum ada materi.", "No materials yet.", "لا توجد مواد بعد."),
    ("confirmDeleteMaterial", "Hapus materi ini?", "Delete this material?", "حذف هذه المادة؟"),
    ("manageQuizTitle", "Kelola Quiz Ramadan", "Manage Ramadan Quiz", "إدارة اختبار رمضان"),
    ("manageQuizSubtitle", "Buat quiz pilihan ganda dengan penilaian otomatis", "Create multiple choice quizzes with auto-grading", "إنشاء اختبارات اختيار متعدد مع تصحيح تلقائي"),
    ("createQuiz", "Buat Quiz", "Create Quiz", "إنشاء اختبار"),
    ("newQuiz", "Buat Quiz Baru", "Create New Quiz", "إنشاء اختبار جديد"),
    ("editQuizLabel", "Edit Quiz", "Edit Quiz", "تعديل الاختبار"),
    ("quizTitleField", "Judul Quiz", "Quiz Title", "عنوان الاختبار"),
    ("timeLimit", "Batas Waktu (menit)", "Time Limit (minutes)", "الحد الزمني (دقائق)"),
    ("passingScore", "Nilai Minimal Lulus", "Passing Score", "درجة النجاح"),
    ("manageQuestions", "Kelola Soal", "Manage Questions", "إدارة الأسئلة"),
    ("addQuestion", "Tambah Soal", "Add Question", "إضافة سؤال"),
    ("newQuestion", "Soal Baru", "New Question", "سؤال جديد"),
    ("questionText", "Teks soal...", "Question text...", "نص السؤال..."),
    ("pointsLabel", "Poin:", "Points:", "النقاط:"),
    ("answerPlaceholder", "Jawaban {number}", "Answer {number}", "إجابة {number}"),
    ("addAnswer", "+ Tambah jawaban", "+ Add answer", "+ إضافة إجابة"),
    ("saveQuestion", "Simpan Soal", "Save Question", "حفظ السؤال"),
    ("noQuestions", "Belum ada soal.", "No questions yet.", "لا توجد أسئلة بعد."),
    ("quizResults", "Hasil Quiz", "Quiz Results", "نتائج الاختبار"),
    ("passedStatus", "Lulus", "Passed", "ناجح"),
    ("notPassedStatus", "Tidak Lulus", "Not Passed", "غير ناجح"),
    ("noResults", "Belum ada hasil.", "No results yet.", "لا توجد نتائج بعد."),
    ("noQuizzesAvailable", "Belum ada quiz.", "No quizzes yet.", "لا توجد اختبارات بعد."),
    ("successQuizCreated", "Quiz dibuat!", "Quiz created!", "تم إنشاء الاختبار!"),
    ("successQuizUpdated", "Quiz diubah!", "Quiz updated!", "تم تحديث الاختبار!"),
    ("successQuizDeleted", "Quiz dihapus!", "Quiz deleted!", "تم حذف الاختبار!"),
    ("successQuestionAdded", "Soal ditambahkan!", "Question added!", "تمت إضافة السؤال!"),
    ("errorLoadQuiz", "Gagal memuat quiz", "Failed to load quiz", "فشل تحميل الاختبار"),
    ("errorLoadDetail", "Gagal memuat detail quiz", "Failed to load quiz detail", "فشل تحميل تفاصيل الاختبار"),
    ("errorLoadResults", "Gagal memuat hasil", "Failed to load results", "فشل تحميل النتائج"),
    ("errorSaveQuiz", "Gagal menyimpan", "Failed to save", "فشل الحفظ"),
    ("errorDeleteQuiz", "Gagal menghapus", "Failed to delete", "فشل الحذف"),
    ("errorAddQuestion", "Gagal menambah soal", "Failed to add question", "فشل إضافة السؤال"),
    ("questionRequired", "Soal dan minimal 2 jawaban wajib diisi", "Question and at least 2 answers required", "السؤال وإجابتان على الأقل مطلوبان"),
    ("selectCorrectAnswer", "Pilih satu jawaban yang benar", "Select one correct answer", "اختر إجابة صحيحة واحدة"),
    ("minutesLabel", "menit", "minutes", "دقائق"),
    ("monitorJournalTitle", "Monitoring Jurnal Siswa", "Student Journal Monitoring", "مراقبة يوميات الطلاب"),
    ("monitorJournalSubtitle", "Pantau jurnal harian siswa selama Ramadan", "Monitor student daily journals during Ramadan", "مراقبة اليوميات اليومية للطلاب خلال رمضان"),
    ("notFilledYet", "Belum mengisi", "Not filled yet", "لم يملأ بعد"),
    ("noStudentsFound", "Tidak ada siswa ditemukan.", "No students found.", "لم يتم العثور على طلاب."),
    ("noJournalsForStudent", "Siswa ini belum membuat jurnal.", "This student has not written any journals.", "لم يكتب هذا الطالب أي يوميات."),
    ("errorLoadMonitoring", "Gagal memuat data", "Failed to load data", "فشل تحميل البيانات"),
    ("errorLoadStudentJournals", "Gagal memuat jurnal siswa", "Failed to load student journals", "فشل تحميل يوميات الطالب"),
    ("monitorTrackerTitle", "Monitoring Tracker Ibadah", "Worship Tracker Monitoring", "مراقبة متتبع العبادة"),
    ("monitorTrackerSubtitle", "Pantau ibadah siswa, beri komentar dan penilaian", "Monitor student worship, give comments and grades", "مراقبة عبادة الطلاب، إعطاء تعليقات ودرجات"),
    ("fridayPrayerData", "Data Shalat Jumat Siswa", "Student Friday Prayer Data", "بيانات صلاة الجمعة للطلاب"),
    ("khatib", "Khatib", "Khatib", "الخطيب"),
    ("sermonMaterial", "Materi", "Material", "المادة"),
    ("notGraded", "Belum Dinilai", "Not Graded", "لم يتم التقييم"),
    ("gradeValue", "Nilai", "Grade", "الدرجة"),
    ("editGrade", "Edit", "Edit", "تعديل"),
    ("sermonSummary", "Ringkasan Khotbah", "Sermon Summary", "ملخص الخطبة"),
    ("lesson", "Pelajaran", "Lesson", "الدرس"),
    ("giveComment", "Beri Komentar & Nilai", "Give Comment & Grade", "إعطاء تعليق ودرجة"),
    ("commentLabel", "Komentar", "Comment", "تعليق"),
    ("commentPlaceholder", "Tulis komentar untuk siswa...", "Write a comment for the student...", "اكتب تعليقاً للطالب..."),
    ("scoreLabel", "Nilai (0-100):", "Score (0-100):", "الدرجة (0-100):"),
    ("saveGrade", "Simpan Penilaian", "Save Grade", "حفظ التقييم"),
    ("cancelGrade", "Batal", "Cancel", "إلغاء"),
    ("teacherComment", "Komentar Guru", "Teacher Comment", "تعليق المعلم"),
    ("noFridayPrayerData", "Belum ada data Shalat Jumat.", "No Friday Prayer data.", "لا توجد بيانات صلاة الجمعة."),
    ("errorLoadTracker", "Gagal memuat data", "Failed to load data", "فشل تحميل البيانات"),
    ("nisField", "NIS/NISN", "Student ID/NISN", "رقم الطالب/NISN"),
    ("nipField", "NIP/Username", "Teacher ID/Username", "رقم المعلم/اسم المستخدم"),
    ("nisPlaceholder", "Masukkan NIS/NISN", "Enter Student ID/NISN", "أدخل رقم الطالب/NISN"),
    ("nipPlaceholder", "Masukkan NIP/Username", "Enter Teacher ID/Username", "أدخل رقم المعلم/اسم المستخدم"),
]

for key, id_val, en_val, ar_val in new_keys:
    id_data[key] = id_val
    en_data[key] = en_val
    ar_data[key] = ar_val

with open(os.path.join(base, 'id.json'), 'w', encoding='utf-8') as f:
    json.dump(id_data, f, ensure_ascii=False, indent=2)
with open(os.path.join(base, 'en.json'), 'w', encoding='utf-8') as f:
    json.dump(en_data, f, ensure_ascii=False, indent=2)
with open(os.path.join(base, 'ar.json'), 'w', encoding='utf-8') as f:
    json.dump(ar_data, f, ensure_ascii=False, indent=2)

print(f"Done. Added {len(new_keys)} keys.")
print(f"id.json: {len(id_data)} keys")
print(f"en.json: {len(en_data)} keys")
print(f"ar.json: {len(ar_data)} keys")
